# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kanban 0.8.1 ruby lib

Gem::Specification.new do |s|
  s.name = "kanban"
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chris Olstrom"]
  s.date = "2015-11-30"
  s.description = "Because your code totally needed an Agile Workflow"
  s.email = "chris@olstrom.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "kanban.gemspec",
    "lib/kanban.rb",
    "lib/kanban/hash_safety.rb",
    "spec/kanban/hash_safety_spec.rb",
    "spec/kanban_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/colstrom/kanban"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Agile Workflow for your code"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["~> 3.2"])
      s.add_runtime_dependency(%q<contracts>, ["~> 0.12"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_development_dependency(%q<reek>, ["~> 3.7"])
      s.add_development_dependency(%q<roodi>, ["~> 5.0"])
      s.add_development_dependency(%q<autotest-standalone>, ["~> 4.5"])
      s.add_development_dependency(%q<rspec-autotest>, ["~> 1.0"])
    else
      s.add_dependency(%q<redis>, ["~> 3.2"])
      s.add_dependency(%q<contracts>, ["~> 0.12"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<reek>, ["~> 3.7"])
      s.add_dependency(%q<roodi>, ["~> 5.0"])
      s.add_dependency(%q<autotest-standalone>, ["~> 4.5"])
      s.add_dependency(%q<rspec-autotest>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<redis>, ["~> 3.2"])
    s.add_dependency(%q<contracts>, ["~> 0.12"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<reek>, ["~> 3.7"])
    s.add_dependency(%q<roodi>, ["~> 5.0"])
    s.add_dependency(%q<autotest-standalone>, ["~> 4.5"])
    s.add_dependency(%q<rspec-autotest>, ["~> 1.0"])
  end
end

